image: "mcr.microsoft.com/dotnet/sdk:5.0"

stages:
  - Build

Build [Linux x64]:
  stage: Build
  tags:
    - Docker
  script:
    - dotnet restore
    - dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -o ./publish/linux-x64
    - mv publish/linux-x64 MumbleBot
  artifacts:
    paths:
      - ./MumbleBot

Build [Windows x64]:
  stage: Build
  tags:
    - Docker
  script:
    - dotnet restore
    - dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true -o ./publish/win-x64
    - mv publish/win-x64/ MumbleBot/
  artifacts:
    paths:
      - ./MumbleBot
