image: "mcr.microsoft.com/dotnet/sdk:5.0"

stages:
  - build
  - sign

linux-x64:
  stage: build
  tags:
    - Docker
  script:
    - dotnet restore
    - dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -o ./publish/linux-x64
  artifacts:
    name: MumbleBot-linux-x64
    paths:
      - ./publish

win-x64:
  stage: build
  tags:
    - Docker
  script:
    - dotnet restore
    - dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true -o ./publish/win-x64
  artifacts:
    name: MumbleBot-win-x64
    paths:
      - ./publish

sign:
  stage: sign
  tags:
    - Linux
    - Docker
  script:
    - "apt-get update && apt-get install -y gpg"
    - "export GPG_TTY=$(tty)"
    - "ls -lhas publish"
    - "gpg --no-tty --batch --yes --import <(cat $GPG_KEY)"
    - "gpg --no-tty --batch --yes --pinentry-mode loopback --output MumbleBot/MumbleBot.exe.sig --detach-sig MumbleBot.exe"
  artifacts:
    name: SignedFiles
    paths:
      - MumbleBot/MumbleBot.exe.sig

