image: "mcr.microsoft.com/dotnet/sdk:5.0"

include:
  template: Jobs/Code-Quality.gitlab-ci.yml

stages:
  - Build
  - CodeQuality

Build [Linux x64]:
  stage: Build
  tags:
    - Docker
  script:
    - dotnet restore
    - dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -o ./publish/linux-x64
    - mv publish/linux-x64 MumbleBot
  artifacts:
    paths:
      - ./MumbleBot

Build [Windows x64]:
  stage: Build
  tags:
    - Docker
  script:
    - dotnet restore
    - dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true -o ./publish/win-x64
    - mv publish/win-x64/ MumbleBot/
  artifacts:
    paths:
      - ./MumbleBot

Code Quality Report:
  stage: CodeQuality
  tags:
    - Docker_6
  artifacts:
    paths: [gl-code-quality-report.json]

Code Quality Report [html]:
  stage: CodeQuality
  extends: Code Quality Report
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]
