image: "mcr.microsoft.com/dotnet/sdk:5.0"

stages:
  - buildlinuxx64
  - buildwinx64

buildlinuxx64:
  stage: buildlinuxx64
  tags:
    - Docker
  script:
    - dotnet restore
    - dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -o ./publish/linux-x64
  artifacts:
    paths:
      - ./publish/linux-x64

buildwinx64:
  stage: buildwinx64
  tags:
    - Docker
  script:
    - dotnet restore
    - dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true -o ./publish/win-x64
  artifacts:
    paths:
      - ./publish/win-64
